[package]
name = "rust-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.5.1"
dotenv = "0.15.0"
serde_json = "1.0.113"
sqlx = { version = "0.7.3", features = ["runtime-async-std", "macros", "postgres"] }


# [workspace]
# members = [
#     "src",
#     "src/app/user"
# ]